VERSION --build-auto-skip 0.8
PROJECT tghanken/playground

build:
    BUILD --auto-skip ./pocket-cellar+build

check:
    BUILD --auto-skip ./pocket-cellar+check

deploy:
    BUILD --auto-skip ./pocket-cellar+deploy
