VERSION --build-auto-skip 0.8
PROJECT tghanken/playground

# Core Targets - Intended to be called by a user
install:
    BUILD ./pocket-cellar+install

build:
    BUILD --auto-skip ./pocket-cellar+build

check:
    BUILD --auto-skip +build
    BUILD --auto-skip ./pocket-cellar+check

fix:
    BUILD ./pocket-cellar+fix

deploy:
    BUILD --auto-skip +check
    BUILD --auto-skip ./pocket-cellar+deploy

deploy-all:
    BUILD --auto-skip +check
    BUILD ./pocket-cellar+deploy-all

# Utility Targets - Intended to be called only by core targets
