VERSION --build-auto-skip 0.8
PROJECT tghanken/playground

MOUNT_CACHE:
    FUNCTION
    CACHE --id user-nix-cache --sharing shared --chmod 0777 /root/.cache/nix

NIX_INSTALL:
    FUNCTION
    RUN apt update -y && \
        apt install curl -y --no-install-recommends && \
        rm -rf /var/cache/apt/archives /var/lib/apt/lists
    DO +MOUNT_CACHE
    RUN curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install linux \
            --extra-conf "sandbox = false" \
            --extra-conf "substituters = https://nix-community.cachix.org https://cache.garnix.io https://cache.nixos.org/" \
            --extra-conf "trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=" \
            --init none \
            --no-confirm
    ENV PATH="${PATH}:/nix/var/nix/profiles/default/bin"
