load("@aspect_rules_js//js:defs.bzl", "js_library")

SRCS = [
    "main.js",
    "preview.js",
]

js_library(
    name = ".storybook",
    srcs = SRCS,
    visibility = ["//projects/pocket-cellar/site:__subpackages__"],
)
