VERSION --build-auto-skip 0.8
PROJECT tghanken/playground
IMPORT github.com/earthly/lib/rust AS rust
FROM ../../base-images/rust+image
DO rust+INIT
DO ../nix+NIX_INSTALL

# Desired checks:
clippy:
    RUN rustup component add clippy

rustfmt:
    RUN rustup component add rustfmt

doctest:
    RUN echo "TODO" && exit 1

nextest:
    RUN echo "TODO" && exit 1

taplo:
    RUN echo "TODO" && exit 1

audit:
    RUN echo "TODO" && exit 1

deny:
    RUN echo "TODO" && exit 1

hakari:
    RUN echo "TODO" && exit 1

udeps:
    RUN echo "TODO" && exit 1

ADD_WASM_TARGET:
    FUNCTION
    RUN rustup target add wasm32-unknown-unknown

ADD_CF_WORKER_TARGET:
    FUNCTION
    DO +ADD_WASM_TARGET
    DO ../nix+MOUNT_CACHE
    RUN nix profile install nixpkgs#wasm-pack nixpkgs#binaryen nixpkgs#worker-build

ADD_WRANGLER_TARGET:
    FUNCTION
    DO +ADD_CF_WORKER_TARGET
    RUN nix profile install nixpkgs#wrangler
