default_job = "check"

[jobs]

[jobs.check]
command = [
    "cargo", "check",
    "--all-targets",
    "--color", "always",
]
need_stdout = false

[jobs.test]
command = [
    "cargo", "nextest", "run", "--color", "always",
]
need_stdout = true

[jobs.doc]
command = ["cargo", "doc", "--color", "always", "--no-deps"]
need_stdout = false

# If the doc compiles, then it opens in your browser and bacon switches
# to the previous job
[jobs.doc-open]
command = ["cargo", "doc", "--color", "always", "--no-deps", "--open"]
need_stdout = false
on_success = "back" # so that we don't open the browser at each change

[jobs.clippy]
command = [
    "cargo", "clippy",
    "--color", "always",
]
need_stdout = false

[keybindings]
d = "job:doc-open"
