default_job = "test"
env.CARGO_TERM_COLOR = "always"
on_change_strategy = "kill_then_restartt"

[jobs]

[jobs.test]
analyzer = "nextest"
command = [
  "cargo",
  "nextest",
  "run",
  "--color",
  "always",
  "--hide-progress-bar",
  "--failure-output",
  "final",
]
need_stdout = true
watch = ["templates", "src_ts"]

# If the doc compiles, then it opens in your browser and bacon switches
# to the previous job
[jobs.doc-open]
command = ["cargo", "doc", "--color", "always", "--no-deps", "--open"]
need_stdout = false
on_success = "back"

[jobs.clippy]
command = ["cargo", "clippy", "--color", "always"]
need_stdout = false
watch = ["templates", "src_ts"]

[keybindings]
c = "job:clippy"
d = "job:doc-open"
t = "job:test"
