services:
  fullstack-server:
    container_name: fullstack-server
    image: "fullstack-rustapp-server-dev:latest"
    env_file: ".env"
    ports:
      - "3031:3031"
    networks:
      - fullstack-rustapp-template
    stop_signal: SIGINT
    restart: unless-stopped
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - fullstack-rustapp-template
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - fullstack-rustapp-template
    restart: unless-stopped

networks:
  fullstack-rustapp-template:
    driver: bridge

volumes:
    postgres:
    pgadmin:
