# fly.toml app configuration file generated for fullstack-rustapp-template on 2024-09-14T13:51:31-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fullstack-rustapp-template'
kill_signal = "SIGINT"
kill_timeout = 20
primary_region = 'sjc'
swap_size_mb = 128

[build]
image = 'fullstack-rustapp-server:latest'

[deploy]
strategy = "canary"

[env]
SENTRY_ENV = "production"
VITE_ASSETS_PATH = "/assets"

[http_service]
auto_start_machines = true
auto_stop_machines = 'stop'
force_https = true
internal_port = 3031
min_machines_running = 0
processes = ['app']

[http_service.concurrency]
soft_limit = 200
type = "requests"

[http_service.http_options]
idle_timeout = 600

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
path = "/healthz"
timeout = "5s"

[[vm]]
size = 'shared-cpu-1x'
