VERSION --build-auto-skip 0.8
PROJECT tghanken/playground

FROM ../../../.earthly/builders/debian-builder+pnpm-builder
WORKDIR /app

# Core Targets - Intended to be called by a user
install:
    BUILD +build

build:
    BUILD +install-deps
    BUILD +typegen
    COPY --dir +install-deps/node_modules .
    COPY +install-deps/package.json .
    COPY +src-files/* .
    COPY --dir +sync/ .
    COPY +typegen/worker-configuration.d.ts ./src/
    RUN pnpm run build
    SAVE ARTIFACT .svelte-kit AS LOCAL .svelte-kit

check:
    BUILD --auto-skip +vitest
    BUILD --auto-skip +playwright
    BUILD --auto-skip +biome

fix:
    FROM +build
    RUN echo "TODO: Implement lint fixes"

deploy:
    COPY --dir +install/node_modules .
    COPY +install/package.json .
    COPY +src-files/* .
    COPY --dir +build/.svelte-kit ./.svelte-kit
    RUN --push --secret CLOUDFLARE_API_TOKEN pnpm run deploy

# Utility Targets - Intended to be called only by core targets
src-files:
    COPY --dir src static .
    COPY \
        postcss.config.js \
        svelte.config.js \
        tailwind.config.ts \
        tsconfig.json \
        vite.config.ts \
        wrangler.toml \
        .
    SAVE ARTIFACT .

install-deps:
    COPY package.json pnpm-lock.yaml .
    RUN --mount type=cache,target=/root/.pnpm-store pnpm install
    SAVE ARTIFACT package.json AS LOCAL package.json
    SAVE ARTIFACT pnpm-lock.yaml AS LOCAL pnpm-lock.yaml
    SAVE ARTIFACT node_modules AS LOCAL node_modules

sync:
    COPY --dir +install-deps/node_modules .
    COPY +install-deps/package.json .
    COPY +src-files/* .
    RUN pnpm run sync
    SAVE ARTIFACT .svelte-kit

typegen:
    COPY --dir +install-deps/node_modules .
    COPY +install-deps/package.json .
    COPY +src-files/* .
    RUN pnpm run typegen
    SAVE ARTIFACT ./src/worker-configuration.d.ts AS LOCAL ./src/worker-configuration.d.ts

# Tests
vitest:
    FROM +build
    RUN pnpm run test:unit -- --run

playwright:
    RUN echo "TODO: Implement playwright tests"

biome:
    RUN echo "TODO: Implement biome tests"
