#:schema node_modules/wrangler/config-schema.json
name = "pocket-cellar-site"
compatibility_date = "2024-09-25"
pages_build_output_dir = ".svelte-kit/cloudflare"
upload_source_maps = true

[observability]
enabled = true

[limits]
cpu_ms = 100

[[services]]
binding = "PRIVATE_API"
service = "pocket-cellar-private-api"
