VERSION --build-auto-skip 0.8
PROJECT tghanken/playground
IMPORT github.com/earthly/lib/rust AS rust

FROM ../../../.earthly/utilities/rust-builder+base
WORKDIR /app

# Core Targets - Intended to be called by a user
build:
    DO ../../../.earthly/utilities/rust-builder+ADD_CF_WORKER_TARGET
    COPY +deps/* .
    DO rust+SET_CACHE_MOUNTS_ENV
    RUN --mount=$EARTHLY_RUST_CARGO_HOME_CACHE --mount=$EARTHLY_RUST_TARGET_CACHE worker-build
    SAVE ARTIFACT ./build

check:
    BUILD --auto-skip +clippy
    BUILD --auto-skip +rustfmt
    BUILD --auto-skip +doctest
    BUILD --auto-skip +nextest
    BUILD --auto-skip +taplo
    BUILD --auto-skip +audit
    BUILD --auto-skip +deny
    BUILD --auto-skip +udeps

fix:
    FROM ../../../.earthly/utilities/rust-builder+check-base
    COPY +deps/* .
    DO ../../../.earthly/utilities/rust-builder+CLIPPY --FIX=fix
    DO ../../../.earthly/utilities/rust-builder+RUSTFMT --FIX=fix
    SAVE ARTIFACT ./src AS LOCAL ./src
    SAVE ARTIFACT ./Cargo.lock AS LOCAL ./Cargo.lock
    SAVE ARTIFACT ./Cargo.toml AS LOCAL ./Cargo.toml
    SAVE ARTIFACT ./wrangler.toml AS LOCAL ./wrangler.toml

deploy:
    DO ../../../.earthly/utilities/rust-builder+ADD_WRANGLER_TARGET
    COPY +deps/* .
    DO rust+SET_CACHE_MOUNTS_ENV
    RUN --push --mount=$EARTHLY_RUST_CARGO_HOME_CACHE --mount=$EARTHLY_RUST_TARGET_CACHE --secret CLOUDFLARE_API_TOKEN wrangler deploy

# Utility Targets - Intended to be called only by core targets
deps:
    COPY --dir src .
    COPY Cargo.lock Cargo.toml wrangler.toml .
    SAVE ARTIFACT .

# Checks
clippy:
    FROM ../../../.earthly/utilities/rust-builder+check-base
    COPY +deps/* .
    DO ../../../.earthly/utilities/rust-builder+CLIPPY

rustfmt:
    FROM ../../../.earthly/utilities/rust-builder+check-base
    COPY +deps/* .
    DO ../../../.earthly/utilities/rust-builder+RUSTFMT

doctest:
    FROM ../../../.earthly/utilities/rust-builder+check-base
    COPY +deps/* .
    DO ../../../.earthly/utilities/rust-builder+DOCTEST

nextest:
    FROM ../../../.earthly/utilities/rust-builder+check-base
    COPY +deps/* .
    DO ../../../.earthly/utilities/rust-builder+NEXTEST

taplo:
    FROM ../../../.earthly/utilities/rust-builder+check-base
    COPY +deps/* .
    DO ../../../.earthly/utilities/rust-builder+TAPLO

audit:
    FROM ../../../.earthly/utilities/rust-builder+check-base
    COPY +deps/* .
    DO ../../../.earthly/utilities/rust-builder+AUDIT

deny:
    FROM ../../../.earthly/utilities/rust-builder+check-base
    COPY +deps/* .
    DO ../../../.earthly/utilities/rust-builder+DENY

udeps:
    FROM ../../../.earthly/utilities/rust-builder+check-base
    COPY +deps/* .
    DO ../../../.earthly/utilities/rust-builder+UDEPS
