load("@aspect_rules_js//js:defs.bzl", "js_library")

SRCS = [
    "project_id",
    "settings.json",
]

js_library(
    name = "project.inlang",
    srcs = SRCS,
    visibility = ["//projects/pocket-cellar/site:__subpackages__"],
)
