VERSION 0.8
PROJECT tghanken/playground
FROM ../../../.earthly/base-images/debian+image

build:
    RUN echo "Building..."

check:
    RUN echo "Checking..."

deploy:
    WAIT
        BUILD ../private-api+deploy
    END
    RUN echo "Deploying..."
