VERSION --build-auto-skip 0.8
PROJECT tghanken/playground
IMPORT github.com/earthly/lib/rust AS rust

FROM ../../../.earthly/utilities/rust-builder+base
WORKDIR /app

# Core Targets - Intended to be called by a user
build:
    DO ../../../.earthly/utilities/rust-builder+ADD_CF_WORKER_TARGET
    COPY +deps/* .
    DO rust+SET_CACHE_MOUNTS_ENV
    RUN --mount=$EARTHLY_RUST_CARGO_HOME_CACHE --mount=$EARTHLY_RUST_TARGET_CACHE worker-build
    SAVE ARTIFACT ./build

check:
    BUILD --auto-skip +clippy
    BUILD --auto-skip +rustfmt
    # BUILD --auto-skip +doctest
    # BUILD --auto-skip +nextest
    # BUILD --auto-skip +taplo
    # BUILD --auto-skip +audit
    # BUILD --auto-skip +deny
    # BUILD --auto-skip +udeps

fix:
    BUILD --auto-skip +clippy --FIX=fix
    BUILD --auto-skip +rustfmt --FIX=fix

deploy:
    DO ../../../.earthly/utilities/rust-builder+ADD_WRANGLER_TARGET
    COPY +deps/* .
    DO rust+SET_CACHE_MOUNTS_ENV
    WAIT
        BUILD --auto-skip ../private-api+deploy
    END
    RUN --push --mount=$EARTHLY_RUST_CARGO_HOME_CACHE --mount=$EARTHLY_RUST_TARGET_CACHE --secret CLOUDFLARE_API_TOKEN wrangler deploy

# Utility Targets - Intended to be called only by core targets
deps:
    COPY --dir src .
    COPY Cargo.lock Cargo.toml wrangler.toml .
    SAVE ARTIFACT .

# Checks
clippy:
    FROM ../../../.earthly/utilities/rust-builder+clippy
    COPY +deps/* .
    ARG FIX
    IF [ -n "$FIX" ]
        DO rust+CARGO --args "clippy --fix --allow-no-vcs"
        SAVE ARTIFACT ./src AS LOCAL ./src
    ELSE
        DO rust+CARGO --args "clippy -- --deny warnings"
    END

rustfmt:
    FROM ../../../.earthly/utilities/rust-builder+rustfmt
    COPY +deps/* .
    ARG FIX
    IF [ -n "$FIX" ]
        DO rust+CARGO --args "fmt"
        SAVE ARTIFACT ./src AS LOCAL ./src
    ELSE
        DO rust+CARGO --args "fmt --check"
    END

doctest:
    FROM ../../../.earthly/utilities/rust-builder+doctest
    COPY +deps/* .
    DO rust+CARGO --args "test"

nextest:
    FROM ../../../.earthly/utilities/rust-builder+nextest
    COPY +deps/* .
    DO rust+CARGO --args "nextest"

taplo:
    FROM ../../../.earthly/utilities/rust-builder+taplo
    COPY +deps/* .
    DO rust+CARGO --args "taplo fmt"

audit:
    FROM ../../../.earthly/utilities/rust-builder+audit
    COPY +deps/* .
    DO rust+CARGO --args "audit"

deny:
    FROM ../../../.earthly/utilities/rust-builder+deny
    COPY +deps/* .
    DO rust+CARGO --args "deny"

udeps:
    FROM ../../../.earthly/utilities/rust-builder+udeps
    COPY +deps/* .
    DO rust+CARGO --args "udeps"
