name = "pocket-cellar-public-api"
main = "build/worker/shim.mjs"
compatibility_date = "2024-12-18"
minify = true

[build]
command = "worker-build --release"

[observability]
enabled = true

[limits]
cpu_ms = 100

[[services]]
binding = "PRIVATE_API"
service = "pocket-cellar-private-api"
